<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `df_ecms_infoclass_news`;");
E_C("CREATE TABLE `df_ecms_infoclass_news` (
  `classid` int(10) unsigned NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_ftitle` text NOT NULL,
  `z_ftitle` varchar(255) NOT NULL DEFAULT '',
  `qz_ftitle` varchar(255) NOT NULL DEFAULT '',
  `save_ftitle` varchar(10) NOT NULL DEFAULT '',
  `zz_smalltext` text NOT NULL,
  `z_smalltext` varchar(255) NOT NULL DEFAULT '',
  `qz_smalltext` varchar(255) NOT NULL DEFAULT '',
  `save_smalltext` varchar(10) NOT NULL DEFAULT '',
  `zz_writer` text NOT NULL,
  `z_writer` varchar(255) NOT NULL DEFAULT '',
  `qz_writer` varchar(255) NOT NULL DEFAULT '',
  `save_writer` varchar(10) NOT NULL DEFAULT '',
  `zz_befrom` text NOT NULL,
  `z_befrom` varchar(255) NOT NULL DEFAULT '',
  `qz_befrom` varchar(255) NOT NULL DEFAULT '',
  `save_befrom` varchar(10) NOT NULL DEFAULT '',
  `zz_newstext` text NOT NULL,
  `z_newstext` varchar(255) NOT NULL DEFAULT '',
  `qz_newstext` varchar(255) NOT NULL DEFAULT '',
  `save_newstext` varchar(10) NOT NULL DEFAULT '',
  `zz_diggtop` text NOT NULL,
  `z_diggtop` varchar(255) NOT NULL DEFAULT '',
  `qz_diggtop` varchar(255) NOT NULL DEFAULT '',
  `save_diggtop` varchar(10) NOT NULL DEFAULT '',
  `zz_ywjs` text NOT NULL,
  `z_ywjs` varchar(255) NOT NULL,
  `qz_ywjs` varchar(255) NOT NULL,
  `save_ywjs` varchar(10) NOT NULL,
  `zz_gzlct` text NOT NULL,
  `z_gzlct` varchar(255) NOT NULL,
  `qz_gzlct` varchar(255) NOT NULL,
  `save_gzlct` varchar(10) NOT NULL,
  `zz_ywly` text NOT NULL,
  `z_ywly` varchar(255) NOT NULL,
  `qz_ywly` varchar(255) NOT NULL,
  `save_ywly` varchar(10) NOT NULL,
  `zz_ywlyc` text NOT NULL,
  `z_ywlyc` varchar(255) NOT NULL,
  `qz_ywlyc` varchar(255) NOT NULL,
  `save_ywlyc` varchar(10) NOT NULL,
  `zz_hyyj` text NOT NULL,
  `z_hyyj` varchar(255) NOT NULL,
  `qz_hyyj` varchar(255) NOT NULL,
  `save_hyyj` varchar(10) NOT NULL,
  `zz_hyyjc` text NOT NULL,
  `z_hyyjc` varchar(255) NOT NULL,
  `qz_hyyjc` varchar(255) NOT NULL,
  `save_hyyjc` varchar(10) NOT NULL,
  `zz_fzlc` text NOT NULL,
  `z_fzlc` varchar(255) NOT NULL,
  `qz_fzlc` varchar(255) NOT NULL,
  `save_fzlc` varchar(10) NOT NULL,
  `zz_gsly` text NOT NULL,
  `z_gsly` varchar(255) NOT NULL,
  `qz_gsly` varchar(255) NOT NULL,
  `save_gsly` varchar(10) NOT NULL,
  `zz_zzjg` text NOT NULL,
  `z_zzjg` varchar(255) NOT NULL,
  `qz_zzjg` varchar(255) NOT NULL,
  `save_zzjg` varchar(10) NOT NULL,
  `zz_gsjj` text NOT NULL,
  `z_gsjj` varchar(255) NOT NULL,
  `qz_gsjj` varchar(255) NOT NULL,
  `save_gsjj` varchar(10) NOT NULL,
  `zz_zgs` text NOT NULL,
  `z_zgs` varchar(255) NOT NULL,
  `qz_zgs` varchar(255) NOT NULL,
  `save_zgs` varchar(10) NOT NULL,
  `zz_zonggs` text NOT NULL,
  `z_zonggs` varchar(255) NOT NULL,
  `qz_zonggs` varchar(255) NOT NULL,
  `save_zonggs` varchar(10) NOT NULL,
  `zz_fgs` text NOT NULL,
  `z_fgs` varchar(255) NOT NULL,
  `qz_fgs` varchar(255) NOT NULL,
  `save_fgs` varchar(10) NOT NULL,
  `zz_gszz` text NOT NULL,
  `z_gszz` varchar(255) NOT NULL,
  `qz_gszz` varchar(255) NOT NULL,
  `save_gszz` varchar(10) NOT NULL,
  `zz_zw` text NOT NULL,
  `z_zw` varchar(255) NOT NULL,
  `qz_zw` varchar(255) NOT NULL,
  `save_zw` varchar(10) NOT NULL,
  `zz_bm` text NOT NULL,
  `z_bm` varchar(255) NOT NULL,
  `qz_bm` varchar(255) NOT NULL,
  `save_bm` varchar(10) NOT NULL,
  `zz_gzdd` text NOT NULL,
  `z_gzdd` varchar(255) NOT NULL,
  `qz_gzdd` varchar(255) NOT NULL,
  `save_gzdd` varchar(10) NOT NULL,
  `zz_rs` text NOT NULL,
  `z_rs` varchar(255) NOT NULL,
  `qz_rs` varchar(255) NOT NULL,
  `save_rs` varchar(10) NOT NULL,
  `zz_lxwm` text NOT NULL,
  `z_lxwm` varchar(255) NOT NULL,
  `qz_lxwm` varchar(255) NOT NULL,
  `save_lxwm` varchar(10) NOT NULL,
  `zz_qywh` text NOT NULL,
  `z_qywh` varchar(255) NOT NULL,
  `qz_qywh` varchar(255) NOT NULL,
  `save_qywh` varchar(10) NOT NULL,
  `zz_gsjjl` text NOT NULL,
  `z_gsjjl` varchar(255) NOT NULL,
  `qz_gsjjl` varchar(255) NOT NULL,
  `save_gsjjl` varchar(10) NOT NULL,
  `zz_allx` text NOT NULL,
  `z_allx` varchar(255) NOT NULL,
  `qz_allx` varchar(255) NOT NULL,
  `save_allx` varchar(10) NOT NULL,
  `zz_gydf` text NOT NULL,
  `z_gydf` varchar(255) NOT NULL,
  `qz_gydf` varchar(255) NOT NULL,
  `save_gydf` varchar(10) NOT NULL,
  `zz_qywhnav` text NOT NULL,
  `z_qywhnav` varchar(255) NOT NULL,
  `qz_qywhnav` varchar(255) NOT NULL,
  `save_qywhnav` varchar(10) NOT NULL,
  `zz_ywjsnav` text NOT NULL,
  `z_ywjsnav` varchar(255) NOT NULL,
  `qz_ywjsnav` varchar(255) NOT NULL,
  `save_ywjsnav` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");

@include("../../inc/footer.php");
?>